//////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2015 Autodesk, Inc.  All rights reserved.
//
//  Use of this software is subject to the terms of the Autodesk license 
//  agreement provided at the time of installation or download, or which 
//  otherwise accompanies this software in either electronic or hard copy form.   
//
//////////////////////////////////////////////////////////////////////////////
#pragma once

#include "BaseTranslator_to_RTI.h"
// rti
#include <rti/scene/geometry.h>

namespace Max
{;
namespace RapidRTTranslator
{;

// Translates anything ==> one or more rti::Geometry
// Base class for any translator which creates one or more rti::Geometry
class BaseTranslator_to_RTIGeometry : 
	public BaseTranslator_to_RTI
{
public:

    BaseTranslator_to_RTIGeometry(TranslatorGraphNode& translator_graph_node);
    ~BaseTranslator_to_RTIGeometry();

    // Accesses the outputs generated by this translator
    size_t get_num_output_geometries() const;
    std::pair<rti::GeometryHandle, MtlID> get_output_geometry(const size_t index) const;
     
protected:

    // Pre-allocates the array that will store the geometry outputs
    void allocate_geometry_outputs(const size_t num_geometries);

    // Initializes a geometry output with the given material ID. Returns handle with which the geometry can be edited.
    rti::GeometryHandle initialize_geometry_output(const size_t index, const MtlID material_id);

private:

    class GeometryOutput;
};

}}	// namespace 
