//////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2015 Autodesk, Inc.  All rights reserved.
//
//  Use of this software is subject to the terms of the Autodesk license 
//  agreement provided at the time of installation or download, or which 
//  otherwise accompanies this software in either electronic or hard copy form.   
//
//////////////////////////////////////////////////////////////////////////////
#pragma once

// local includes
#include "BaseTranslator_to_RTI.h"
// rti
#include <rti/scene/Texture.h>
// max sdk
#include <IPoint3.h>

class Texmap;

namespace Max
{;
namespace RapidRTTranslator
{;

// Translates: anything ==> rti::Texture
class BaseTranslator_to_RTITexture :
    public BaseTranslator_to_RTI
{
public:

    BaseTranslator_to_RTITexture(TranslatorGraphNode& translator_graph_node);
    ~BaseTranslator_to_RTITexture();

protected:

    // Accesses the outputs generated by this translator
    rti::TextureHandle get_output_texture(const size_t texture_index) const;
    IPoint3 get_output_texture_resolution(const size_t texture_index) const;

    // Creates the rti::Texture (if needed - if it doesn't already exist) translated by this class, initializes the output on the ITranslatorGraphnode.
    // Multiple textures may be translated as necessary
    rti::TextureHandle initialize_output_texture(const size_t texture_index, const rti::TextureDescriptor& texture_desc);

};

}}	// namespace 
