//////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2015 Autodesk, Inc.  All rights reserved.
//
//  Use of this software is subject to the terms of the Autodesk license 
//  agreement provided at the time of installation or download, or which 
//  otherwise accompanies this software in either electronic or hard copy form.   
//
//////////////////////////////////////////////////////////////////////////////
#pragma once

// Local includes
#include "BaseTranslator_to_RTI.h"
// max sdk
#include <RenderingAPI/Translator/GenericTranslatorKeys.h>
// rti
#include <rti/scene/Framebuffer.h>

namespace Max
{;
namespace RapidRTTranslator
{;

// Translates: to rti::FrameBuffer
class Translator_to_RTIFrameBuffer :
	public BaseTranslator_to_RTI
{
public:

    typedef GenericTranslatorKey_Empty<Translator_to_RTIFrameBuffer> Key;

    Translator_to_RTIFrameBuffer(const Key& key, TranslatorGraphNode& translator_graph_node);
	~Translator_to_RTIFrameBuffer();

    // Accesses the outputs generated by this translator
    rti::FramebufferHandle get_output_frame_buffer() const;

    // -- inherited from Translator
    virtual TranslationResult Translate(const TimeValue t, Interval& validity, ITranslationProgress& translation_progress, KeyframeList& keyframesNeeded) override;
    virtual Interval CheckValidity(const TimeValue t, const Interval& previous_validity) const override;
    virtual void PreTranslate(const TimeValue translationTime, Interval& validity) override;
    virtual void PostTranslate(const TimeValue translationTime, Interval& validity) override;
    virtual MSTR GetTimingCategory() const override;
};

}}	// namespace 
